import test from 'node:test';import assert from 'node:assert/strict';
import {validate} from '../web/lib/validate.mjs';
import {POST} from '../web/app/api/requests/route.js';
const input={request_id:' req-1001 ',requester_email:'DEMO@example.com',category:' Access ',description:'I cannot   access the knowledge repository',business_impact:'single_user',urgency:'normal'};
let seq=0;function req(data,headers={}){return new Request('http://localhost/api/requests',{method:'POST',headers:{'Content-Type':'application/json','x-forwarded-for':String(++seq),...headers},body:JSON.stringify(data)});}
test('normalization and invalid fields',()=>{const v=validate(input);assert.deepEqual(v.errors,[]);assert.equal(v.request.category,'access');assert.equal(v.request.request_id,'REQ-1001');for(const x of [{...input,urgency:'critical'},{...input,requester_email:'invalid'},{...input,description:'short'},null])assert.ok(validate(x).errors.length);});
test('public simulation never calls workflow',async()=>{const old=global.fetch;global.fetch=()=>{throw Error('unexpected network')};try{const r=await POST(req(input,{host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000'}));assert.equal(r.status,200);assert.equal((await r.json()).outcome,'simulated');}finally{global.fetch=old;}});
test('real mode rejects wrong code and cross-origin',async()=>{process.env.DEMO_ACCESS_CODE='test-only-access-code';assert.equal((await POST(req({...input,mode:'real',access_code:'bad'}))).status,403);assert.equal((await POST(req(input,{origin:'https://evil.invalid'}))).status,403);});
test('invalid input and payload bounds',async()=>{assert.equal((await POST(req({...input,category:'oops'}))).status,422);assert.equal((await POST(req({...input,description:'a'.repeat(9000)}))).status,413);});
test('authorized forwarding strips code, returns partial success, never leaks secret',async()=>{process.env.DEMO_ACCESS_CODE='test-only-access-code';process.env.N8N_WEBHOOK_URL='https://test.invalid/webhook/supportflow';process.env.N8N_WEBHOOK_SECRET='local-test-secret';const old=global.fetch;global.fetch=async(url,options)=>{assert.equal(options.headers.Authorization,'Bearer local-test-secret');assert.equal(JSON.parse(options.body).access_code,undefined);return Response.json({request_id:'REQ-1001',priority:'P3',outcome:'notification_failed',ticket_url:'https://github.com/demo/test/issues/1',mode:'real',secret:'should not return'},{status:207});};try{const r=await POST(req({...input,mode:'real',access_code:'test-only-access-code'}));assert.equal(r.status,207);assert.equal((await r.json()).secret,undefined);}finally{global.fetch=old;}});
test('upstream timeout means unknown, not failed ticket',async()=>{const old=global.fetch;global.fetch=async()=>{const e=Error();e.name='TimeoutError';throw e;};try{const r=await POST(req({...input,mode:'real',access_code:'test-only-access-code'}));assert.equal(r.status,504);assert.equal((await r.json()).outcome,'timeout_unknown');}finally{global.fetch=old;}});
test('per-instance request limit',async()=>{let r;for(let i=0;i<11;i++)r=await POST(req(input,{'x-forwarded-for':'limit-test'}));assert.equal(r.status,429);});
